### ISSUE TITLE
Implement multi account?

### ISSUE THREAD

**Issue by kotik1998** [SloRunner/node-steam-donation-bot#1]
Can you add multi-user support?

**Comment by SloRunner** [comment]
gonna work on this when i have some free time 👍

**Comment by kotik1998** [comment]
take a look what ive found on UnknownCheats Forums ( https://www.unknowncheats.me/forum/counterstrike-global-offensive/201270-ez-steam-hours-booster.html ) it's multi account but doesnt have trading options, i think this might help implementing :)

**Comment by SloRunner** [comment]
i started working on it, and yeah it will be helpfull :) btw you can add me on steam, it's in the readme of this repo

**Comment by kotik1998** [comment]
done, my name is Vik on steam

**Comment by SloRunner** [comment]
agreed to private version, closing issue
